name: vadrugdev
dependencies:
    - python=2.7.12
    - nose=1.3.7
    - pandas=0.19.2
    - xlrd=1.0.0
    - pip:
        - git+https://github.com/jcrudy/clinvoc.git@86acb4a12ca9d5de893e7f7bf7ab0405eaedf9c7